## This configuration was generated by terraform-provider-oci

resource oci_bastion_bastion test_bastion {
  # Only create bastion if there is subnet
  count = var.accessSubnet == "N/A" ? 0 : 1
  bastion_type = "STANDARD"
  # Allow access from any where
  client_cidr_block_allow_list = [
    "0.0.0.0/0",
  ]
  compartment_id = var.compartment_ocid
  #Enable SOCKS5 tunnel
  dns_proxy_status = "ENABLED"
  target_subnet_id = var.accessSubnet
  name           = "${data.oci_identity_compartment.test_compartment.name}Bastion"
}

